### ISSUE TITLE
Copyright question regarding 3D models in the examples

### ISSUE THREAD

**Issue by MChangFoundry** [pmndrs/examples#10]
Per the title, are the 3D models in the examples copyrighted? If not, is there any information on the license for them?

**Comment by MChangFoundry** [comment]
@abernier Love your monitors example btw! Do you own the 3D assets used in that example?

**Comment by abernier** [comment]
authors of apps/* are the owner of the historic CSB defined in the link you have into apps/*/package.json#homepage eg:

https://github.com/pmndrs/examples/blob/bcf2ceb55a26a5ecb272fc396a3ca919f922e7c7/apps/monitors/package.json#L5

license are referenced directly into the code, eg:

https://github.com/pmndrs/examples/blob/bcf2ceb55a26a5ecb272fc396a3ca919f922e7c7/apps/monitors/src/Computers.jsx#L14-L19
