### ISSUE TITLE
broken demos (errors in console)

### ISSUE THREAD

**Issue by abernier** [pmndrs/examples#18]
they build BUT they are errors in console

TODO: list them here

- [x] https://pmndrs.github.io/examples/demos/arkanoid
- [ ] https://pmndrs.github.io/examples/demos/basic-ballpit

**Comment by abernier** [comment]
@rndexe could you submit a pr for this fix? You can test any demo running:

```sh
$ npm run -w demos/csg-house dev
```

**Comment by rndexe** [comment]
Sure. I might try to fix a few other demos as well. Do you think I should submit PRs individually or combined?

**Comment by abernier** [comment]
would say individually:) ty

**Comment by abernier** [comment]
superseded by https://github.com/pmndrs/examples/issues/38
