### ISSUE TITLE
better ui

### ISSUE THREAD

**Issue by abernier** [pmndrs/examples#37]
- [x] open-props trash tailwind in favor of [open-props w/ `@scope`](https://discord.com/channels/896960631322849340/896960787099299850/1268536803938537492)[^1] plain css -- https://github.com/pmndrs/examples/pull/55
- [x] responsive support (horizontal/vertical nav)
- [x] centered-nav
- [x] badges:
  - source code (github) -- https://github.com/pmndrs/examples/tree/main/demos/video-cookies
  - links: 
    - embed -- https://pmndrs.github.io/examples/video-cookies/
    - csb -- https://codesandbox.io/s/github/pmndrs/examples/tree/main/demos/video-cookies
    - stackblitz -- https://stackblitz.com/github/pmndrs/examples/tree/main/demos/video-cookies
  - degit command -- `npx -y degit pmndrs/examples/demos/video-cookies`
  
[^1]: https://github.com/vercel/next.js/discussions/68504

**Comment by abernier** [comment]
svg icons https://react-svgr.com/docs/next/

**Comment by zanhk** [comment]
Really love this collection, very easy to navigate! Nice stuff
