### ISSUE TITLE
Grass shader bug

### ISSUE THREAD

**Issue by hichemfantar** [pmndrs/examples#81]
https://github.com/pmndrs/examples/tree/main/demos/grass-shader

there's a bug with the grass shader example where the grass isn't rendered on certain camera angles

https://github.com/user-attachments/assets/d51b47b7-de6c-45e8-b674-645ba11053db

**Comment by abernier** [comment]
I cannot reproduce on my setup (macos 15 m1 / Chrome latest)

**Comment by abernier** [comment]
yeah even on different camera angles/positions

**Comment by abernier** [comment]
can you create a PR to fix it?

**Comment by hichemfantar** [comment]
setting frustumCulled={false} fixes it but im not sure it's a real fix

**Comment by hichemfantar** [comment]
discord discussion link https://discord.com/channels/740090768164651008/741751532592038022/1275865580523753494

**Comment by isaac-mason** [comment]
You can reproduce it by positioning the camera not to look at the center of the grass.

 The grass geometry needs a bounding sphere sphere manually set as the grass blades are positioned in the shader.

<img width="1487" alt="image" src="https://github.com/user-attachments/assets/9e806e37-6468-4791-97cf-6c0b9c90ff6b">

**Comment by hichemfantar** [comment]
thanks for the fix @isaac-mason

**Comment by isaac-mason** [comment]
No worries!
